### ISSUE TITLE
error about pcl when make

### ISSUE THREAD

**Issue by shammmmmless** [kanster/RGBD-Segmenter#3]
In file included from /home/user/Cworkspace/RGBD-Segmenter/v4r/GraphCut.h:47:0,
                 from /home/user/Cworkspace/RGBD-Segmenter/v4r/GraphCut.cpp:33:
/home/user/Cworkspace/RGBD-Segmenter/v4r/SurfaceModel.hpp:36:52: fatal error: **pcl/surface/on_nurbs/sequential_fitter.h: No such file or directory**
compilation terminated.
v4r/CMakeFiles/v4rSegmenterLight.dir/build.make:86: recipe for target 'v4r/CMakeFiles/v4rSegmenterLight.dir/GraphCut.cpp.o' failed
make[2]: *** [v4r/CMakeFiles/v4rSegmenterLight.dir/GraphCut.cpp.o] Error 1
CMakeFiles/Makefile2:121: recipe for target 'v4r/CMakeFiles/v4rSegmenterLight.dir/all' failed
make[1]: *** [v4r/CMakeFiles/v4rSegmenterLight.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I used both pcl1.7 and 1.8, they dont have this file, could you tell me which version should I use or other way to fix it?

**Comment by shammmmmless** [comment]
fix by add -DBUILD_surface_no_nurbs=True when cmake pcl.

**Comment by juanmed** [comment]
the correct flag is ```-DBUILD_surface_on_nurbs=True```. Notice "on" instead of "no".
